import time
print('mise à feu!')
print('o.oui/n.non')
play=input('veux-tu voir les credits:')
if play==('o'):
 time.sleep(1)
 print('credit de mise à feu bêtà V1.1')
 time.sleep(3)
 print('crédit de début.')
 time.sleep(2)
 print('seul dévlopper+bêtà testeur:caperuisseau_(pseudo)')
 time.sleep(2)
 print('bêtà testeuse:victoire_974(pseudo)')
 time.sleep(2)
 print('folow moi sur itch.io!')
 time.sleep(3)
 print('Merci de jouer à mon jeu !')
 time.sleep(2)
 print('Depuis que je commence à peine à programmer.')
 time.sleep(3)
play=input('commencer le jeu?(o.oui/n.non :')
if play==('o'):
  n=10
  while n>0:
    print(n)
    time.sleep(1)
    n=n-1
  print('mise à feu!')
  time.sleep(1)
  print('Attends, tu es toujours là')
  time.sleep(1)
  print('Eh bien... Ils vous oublient.')
  time.sleep(1)
  print('Haut-parleurs :[DIFFUSION TERMINÉE...LANCEMENT DE LA ROQUETTE RÉUSSI]')
  time.sleep(3)
  print('Vous rentrez chez vous.')
  time.sleep(2)
  print('Les gens vous regardent, nerveux.')
  time.sleep(3)
  print('Maintenant tout le monde pense que tu es un menteur.')
  time.sleep(3)
  print('Conseils : Entrez a/b/c pour répondre.')
  print('Ce que vous choisissez changera la fin.')
  answer=input('Choisis ton destin (a.Travaille plus fort/b.Abandonne/c.S*icide:')
  if answer==('a'):
    time.sleep(2)
    print('Après de nombreuses heures de travail, vous avez enfin une seconde chance.')
    time.sleep(3)
    print('===========Bonne fin===========')
    time.sleep(3)
    print('e')
  if answer==('b'):
    time.sleep(2)
    print('Vous travaillez comme un travailleur normal à la NASA.')
    time.sleep(3)
    print('===========Fin normale==========')
    time.Sleep(3)
    print('e')
  if answer==('c'):
    time.sleep(2)
    print('Tu choisis de mourir...')
    time.sleep(2)
    print('dommage...')
    time.sleep(1)
    print(' très dommage')
    print('pour une si belle vie!')
    time.sleep(2)
    print('===========très mauvaise fin===========')
    time.sleep(3)
    print('e')
